# Generated by Django 3.2.9 on 2021-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Username')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Profile Picture')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('address', models.TextField()),
            ],
        ),
    ]
