# Generated by Django 3.2.9 on 2021-11-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_comment_favoritelist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
