# Generated by Django 3.2 on 2021-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211110_1826'),
        ('customer', '0004_auto_20211110_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='products',
            field=models.ManyToManyField(to='product.Product', verbose_name='Products'),
        ),
    ]
